language: java

matrix:
 include: 
  - node_js: "5"
  - node_js: "4.2"

before_install: 
  - npm install -g bower
  - bower install

script: 
  - gulp ci
  - 'if ["${TRAVIS_NODE_VERSION}" = "4.2"]; then gulp protractor; fi'

